optionsCitiesToConect = [
    "Mountain",
    "Piedmont",
    "Ammo",
    "BBQ",
    "Ranch",
    "Barley",
    "Hops",
    "Glinda",
    "MIT",
    "Bill",
    "Earnhardt",
    "Cub",
    "Wrigley",
    "Brown",
    "Coney Dog",
    "The L",
    "Florida Man",
    "Snow",
    "Grand Central",
    "Vice",
    "Situation",
    "Empire",
    "Gotham",
    "Tofu Driver",
    "Insomnia",
    "Cuban Sandwich",
    "Oregon Trail",
    "Bagel Poutine",
    "Expo 67",
    "Comfort Zone",
    "The 6",
    "Blue Lagoon",
    "Fuzzy Pony",
    "Precedent",
    "Fresh Prince",
    "Cheese",
    "Hawkins",
    "Casino" "Cube",
    "Dogg",
    "Eazy",
    "Lamar",
    "Pac",
    "Floatie",
    "Sanitation",
    "Santana",
    "Inside",
    "Cobain",
    "Cornell",
    "Hendrix",
    "Radiohall",
    "Crosby",
    "Granville",
    "Stanley",
    "Vansterdam",
    "Mansbridge",
    "Boltzmann",
    "Hofburg",
    "Guildhouse",
    "Nevski",
    "Tkalciceva",
    "Staromak",
    "Vltava",
    "LEGO",
    "Lennujaam",
    "Sauna",
    "Tram",
    "Jardin",
    "Seine",
    "Castle",
    "Wurstchen",
    "Agora",
    "Odeon",
    "Danube",
    "Yam Park",
    "Red Light",
    "No Vampires",
    "Devin Castle",
    "Keeper Willie",
    "The Tube",
    "Kaiju",
    "Tango",
    "Mercadao",
    "Pinacoteca",
    "Cueca",
    "Rololandia",
    "Cuy",
    "Crudo",
    "Cojones",
    "Papers",
    "Amaru",
    "Station",
    "Hangang",
    "Datong",
    "Hangover",
    "Khalifa",
    "SMRT",
    "Bukhansan",
    "Bosozoku",
    "Drift",
    "Perdana",
    "Pasig",
    "Garden",
    "Phooey",
    "Victoria",
    "Menteng",
    "Squidney",
    "Hauraki",
    "Parnell",
    "Yarra",
    "Herdsman",
    "Hermitage",
    "Shnur",
    "Rakia",
    "District",
    "Lindfield",
    "Mandela",
    "Teleferik",
    "Ataturk",
    "Galata",
    "Ghost",
    "Lofty",
    "Oval",
    "Tayelet",
    "Duomo",
    "Galleria",
    "Colosseum",
    "Daugava",
    "Saeima",
    "Talksa",
    "Neris",
    "Chemin",
    "Dendrarium",
    "Bicycle",
    "Canal",
    "Reyka",
    "Dullahan",
    "Grafton",
    "Guinness",
    "Tulip",
    "Vardar",
    "Fjord",
    "Motlawa",
    "Curie",
    "Vistula",
    "Bairro",
]
